// AUTO-GENERATED by `node bccm syncsdk` — do not edit; regenerated on each sync.
// The installed @braincloud/client build ships no TypeScript types (the
// published npm package currently has none), so declare the module to keep
// this example compiling. Re-syncing against a typed build removes this file.
declare module '@braincloud/client';
declare module 'braincloud';
